#!/bin/sh

sudo truncate -s 0 -c /var/log/mysql/mariadb-slow.log

git pull

# mariadb の設定をコピーする
sudo cp ~/webapp/conf/mysql/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf

sudo systemctl restart mariadb
